<?php

namespace Cinemino\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cinemino\SiteBundle\Entity\Film;
use Cinemino\SiteBundle\Entity\Media;
use Cinemino\SiteBundle\Entity\CineminoUser;
/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemaRepository extends EntityRepository
{

    public function getCineAutorise($user)
    {
        $qb = $this->createQueryBuilder('c');
        $roles = $user->getRoles();
        if ($roles[0]=='ROLE_PROGRAMMATEUR') 
        { 
                $qb->where('c.idCompte = '. $user->getId());
        }
        
        return $qb;
    }
}