<?php

namespace Cinemino\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cinemino\SiteBundle\Entity\EvenementRepository;
use Cinemino\SiteBundle\Entity\EvenementAssocie;

/**
 * EvenementAssocieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementAssocieRepository extends EvenementRepository
{
}