<?php

namespace Cinemino\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Cinemino\SiteBundle\Entity\Intervenat;
use Cinemino\SiteBundle\Entity\MediaIntervenant;

/**
 * MEdiaIntervenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaIntervenantRepository extends EntityRepository
{
    public function findAlltrie() {
        return $this->createQueryBuilder('m')
                ->orderBy('m.idInter','asc')
                ->getQuery()
                ->getResult();
    }
}