Cinema:
    type: entity
    table: cinema
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        nomCinema:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: NOM_CINEMA
        photo:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: PHOTO
        logo:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: LOGO
        adresse:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: ADRESSE
        adresseMail:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: ADRESSE_MAIL
        coordonneesTel:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: COORDONNEES_TEL
        siteWeb:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: SITE_WEB
        couleurFondCinema:
            type: string
            length: 15
            fixed: false
            nullable: true
            column: COULEUR_FOND_CINEMA
        type:
            type: string
            length: 1
            fixed: false
            nullable: false
            column: TYPE
    manyToMany:
        idCinema:
            targetEntity: Cinema
            cascade: {  }
            mappedBy: cinCinema
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        idCompte:
            targetEntity: CineminoUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_COMPTE:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
