cinema:
    pattern:  /
    defaults: { _controller: "CineminoSiteBundle:Cinema:index" }

cinema_show:
    pattern:  /{id}/show
    defaults: { _controller: "CineminoSiteBundle:Cinema:show" }

cinema_new:
    pattern:  /new
    defaults: { _controller: "CineminoSiteBundle:Cinema:new" }

cinema_create:
    pattern:  /create
    defaults: { _controller: "CineminoSiteBundle:Cinema:create" }
    requirements: { _method: post }

cinema_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CineminoSiteBundle:Cinema:edit" }

cinema_update:
    pattern:  /{id}/update
    defaults: { _controller: "CineminoSiteBundle:Cinema:update" }
    requirements: { _method: post }

cinema_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CineminoSiteBundle:Cinema:delete" }
    requirements: { _method: post }
