media:
    pattern:  /
    defaults: { _controller: "CineminoSiteBundle:Media:index" }

media_show:
    pattern:  /{id}/show
    defaults: { _controller: "CineminoSiteBundle:Media:show" }

mediafilm_new:
    pattern:  /newmfilm
    defaults: { _controller: "CineminoSiteBundle:Media:newfilm" }

mediaevt_new:
    pattern:  /newmevt
    defaults: { _controller: "CineminoSiteBundle:Media:newevt" }
    
mediafilm_create:
    pattern:  /create
    defaults: { _controller: "CineminoSiteBundle:Media:createfilm" }
    requirements: { _method: post }
    
mediaevt_create:
    pattern:  /create
    defaults: { _controller: "CineminoSiteBundle:Media:createevt" }
    requirements: { _method: post }

mediafilm_edit:
    pattern:  /{id}/editmfilm
    defaults: { _controller: "CineminoSiteBundle:Media:editfilm" }
    
mediaevt_edit:
    pattern:  /{id}/editmevt
    defaults: { _controller: "CineminoSiteBundle:Media:editevt" }

mediafilm_update:
    pattern:  /{id}/update
    defaults: { _controller: "CineminoSiteBundle:Media:updatefilm" }
    requirements: { _method: post }

mediaevt_update:
    pattern:  /{id}/update
    defaults: { _controller: "CineminoSiteBundle:Media:updateevt" }
    requirements: { _method: post }
    
media_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CineminoSiteBundle:Media:delete" }
    requirements: { _method: post }
