media:
    pattern:  /
    defaults: { _controller: "CineminoSiteBundle:Media:index" }

mediaFilm_show:
    pattern:  /{id}/show
    defaults: { _controller: "CineminoSiteBundle:MediaFilm:show" }
mediaEvt_show:
    pattern:  /{id}/show
    defaults: { _controller: "CineminoSiteBundle:MediaEvt:show" }
mediaFilm_new:
    pattern:  /film
    defaults: { _controller: "CineminoSiteBundle:MediaFilm:new" }

mediaEvt_new:
    pattern:  /new
    defaults: { _controller: "CineminoSiteBundle:MediaEvt:new" }
    
mediaFilm_create:
    pattern:  /create
    defaults: { _controller: "CineminoSiteBundle:MediaFilm:create" }
    requirements: { _method: post }
    
mediaEvt_create:
    pattern:  /create
    defaults: { _controller: "CineminoSiteBundle:MediaEvt:create" }
    requirements: { _method: post }

mediaFilm_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CineminoSiteBundle:MediaFilm:edit" }
    
mediaEvt_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CineminoSiteBundle:MediaEvt:edit" }

mediaFilm_update:
    pattern:  /{id}/update
    defaults: { _controller: "CineminoSiteBundle:MediaFilm:update" }
    requirements: { _method: post }

mediaEvt_update:
    pattern:  /{id}/update
    defaults: { _controller: "CineminoSiteBundle:MediaEvt:update" }
    requirements: { _method: post }
    
media_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CineminoSiteBundle:Media:delete" }
    requirements: { _method: post }
mediaFilm_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CineminoSiteBundle:MediaFilm:delete" }
    requirements: { _method: post }
mediaEvt_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CineminoSiteBundle:MediaEvt:delete" }
    requirements: { _method: post }