seance:
    pattern:  /
    defaults: { _controller: "CineminoSiteBundle:Seance:index" }

seance_show:
    pattern:  /{id}/show
    defaults: { _controller: "CineminoSiteBundle:Seance:show" }

seance_new:
    pattern:  /new
    defaults: { _controller: "CineminoSiteBundle:Seance:new" }

seance_create:
    pattern:  /create
    defaults: { _controller: "CineminoSiteBundle:Seance:create" }
    requirements: { _method: post }

seance_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CineminoSiteBundle:Seance:edit" }

seance_update:
    pattern:  /{id}/update
    defaults: { _controller: "CineminoSiteBundle:Seance:update" }
    requirements: { _method: post }

seance_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CineminoSiteBundle:Seance:delete" }
    requirements: { _method: post }
