<?php

namespace Cinemino\testBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TestController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cinemino\testBundle\Controller\TestController();
        return $instance;
    }
}
