<?php

namespace Cinemino\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProgrammeCourtsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cinemino\SiteBundle\Controller\ProgrammeCourtsController();
        return $instance;
    }
}
