cineminoSite_front:
    resource: "routing/front.yml"
    prefix:   /

cineminoSite_back:
    pattern:  /backoffice
    defaults: { _controller: CineminoSiteBundle:Back:index }


cineminoSite_cinema:
    resource: "routing/cinema.yml"
    prefix:   /backoffice/cinema
    
cineminoSite_users:
    resource: "routing/cineminouser.yml"
    prefix:   /backoffice/utilisateurs
    
CineminoSite_intervenant:
        resource: "routing/intervenant.yml"
        prefix:   /backoffice/intervenant
        
CineminoSite_seance:
        resource: "routing/seance.yml"
        prefix:   /backoffice/seance
        
CineminoSite_film:
        resource: "routing/film.yml"
        prefix:   /backoffice/film

CineminoSite_media:
        resource: "routing/media.yml"
        prefix:   /backoffice/media
        
CineminoSite_mediafilm:
        resource: "routing/mediafilm.yml"
        prefix:   /backoffice/mediafilm

CineminoSite_mediaintervenant:
        resource: "routing/mediaintervenant.yml"
        prefix:   /backoffice/mediaintervenant
        
CineminoSite_mediaevt:
        resource: "routing/mediaevt.yml"
        prefix:   /backoffice/mediaevt
             
CineminoSiteBundle_evenement:
        resource: "routing/evenement.yml"
        prefix:   /backoffice/evenement
        
CineminoSiteBundle_evenementassocie:
        resource: "routing/evenementassocie.yml"
        prefix:   /backoffice/evenementassocie        

CineminoSiteBundle_sponsor:
        resource: "routing/sponsor.yml"
        prefix:   /backoffice/sponsor

CineminoSiteBundle_document:
        resource: "@CineminoSiteBundle/Resources/config/routing/document.yml"
        prefix:   /backoffice/document

CineminoSiteBundle_programmecourts:
        resource: "@CineminoSiteBundle/Resources/config/routing/programmecourts.yml"
        prefix:   /backoffice/programmecourts

CineminoSiteBundle_newsletter:
        resource: "@CineminoSiteBundle/Resources/config/routing/newsletter.yml"
        prefix:   /backoffice/newsletter
        
CineminoSiteBundle_typeevenement:
        resource: "@CineminoSiteBundle/Resources/config/routing/typeevenement.yml"
        prefix:   /backoffice/typeevenement
        
CineminoSiteBundle_mediain:
        resource: "@CineminoSiteBundle/Resources/config/routing/mediain.yml"
        prefix:   /backoffice/mediain
        
CineminoSiteBundle_cinemino:
        resource: "@CineminoSiteBundle/Resources/config/routing/cinemino.yml"
        prefix:   /backoffice/cinemino